# -*- mode: python ; coding: utf-8 -*-
import os

block_cipher = None
base = os.path.abspath('.')

a = Analysis(
    ['launcher.py'],
    pathex=[base],
    binaries=[],
    datas=[
        ('app/templates', 'app/templates'),
        ('app/static', 'app/static'),
        ('.env.example', '.'),
    ],
    hiddenimports=[
        'app',
        'app.main',
        'app.config',
        'app.database',
        'app.models',
        'app.scrapers',
        'app.scrapers.amazon',
        'app.scrapers.tiktok',
        'app.scrapers.mercadolibre',
        'app.scrapers.google_trends',
        'app.services',
        'app.services.discovery',
        'app.services.gap_analysis',
        'app.services.translator',
        'app.services.supplier',
        'app.services.landing_page',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
        'uvicorn.lifespan.off',
        'fastapi',
        'starlette',
        'starlette.responses',
        'starlette.routing',
        'starlette.middleware',
        'starlette.staticfiles',
        'starlette.templating',
        'sqlalchemy',
        'sqlalchemy.ext.asyncio',
        'sqlalchemy.dialects.sqlite',
        'aiosqlite',
        'jinja2',
        'httpx',
        'bs4',
        'anthropic',
        'dotenv',
        'multipart',
        'anyio',
        'anyio._backends',
        'anyio._backends._asyncio',
        'sniffio',
        'httpcore',
        'certifi',
        'h11',
        'idna',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['tkinter', 'matplotlib', 'numpy', 'pandas', 'scipy', 'PIL', 'pytrends'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='NewMarkets',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
